version: '3.8'
volumes:
  db-data:
    driver: local
services:
  app:
    image: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/vvnuts
    ports:
      - '8080:8080'
  service-db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vvnuts
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/data:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data